apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      project: www
      app: java-demo
  template:
    metadata:
      labels:
        project: www
        app: java-demo
    spec:
      containers:
      - image: zjklzhao/maven-htmx
        name: java-demo
        command: ["/bin/bash", "-ce", "tail -f /dev/null", "java", "-jar", "/webapp/htmx-demo.jar"]
        resources:
          requests:
            cpu: 0.5
            memory: 500Mi
          limits: 
            cpu: 1
            memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: java-demo 
spec:
  selector:
    project: www
    app: java-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
