apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
  namespace: NS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
      - name: java-demo
      image: $IMAGE_NAME
      ports:
      - containerPort: 8080
            
---
 
apiVersion: v1
kind: Service
metadata:
  namespace: NS
  name: java-demo
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-demo
